#!/bin/sh

# Reference: https://git-scm.com/docs/githooks#_prepare_commit_msg

set -u

trap 'rm -f ${MESSAGE_FILE}' EXIT

readonly MESSAGE_SOURCE=${2:-none}
readonly MESSAGE_FILE=$(mktemp /tmp/commit-message-XXXX)
readonly ISSUE=$(git rev-parse --abbrev-ref HEAD 2>/dev/null | sed -e 's#.*/##g')

case ${MESSAGE_SOURCE} in
    commit|merge|squash|template)
        exit 0
        ;;
    message)
        echo "[${ISSUE}] $(head -1 $1)" > ${MESSAGE_FILE}
        tail -n +2 $1 >> ${MESSAGE_FILE}
        ;;
    none)
        echo "[${ISSUE}] <you must have a one-line banner-type message here>" > ${MESSAGE_FILE}
        cat $1 >> ${MESSAGE_FILE}
        ;;
esac

cat ${MESSAGE_FILE} > $1
